cloud_self_filter_node:
  ros__parameters:
    cloud_in: "/fastlio2/world_cloud"
    cloud_out: "/cloud_registered_filtered"
    odom_topic: "/fastlio2/lio_odom"

    use_odom: true

    # 过滤飞机自身附近点云
    enable_self_filter: true
    self_filter_radius: 0.60

    # 距离过滤，基于当前 odom 位置
    enable_range_filter: true
    min_range: 0.10
    max_range: 6.00

    # 高度过滤默认关闭，避免误删细杆/地面点
    enable_z_filter:
    z_relative_to_odom: true
    min_z_keep: 0.2
    max_z_keep:1.5

    # 体素降采样
    enable_voxel_filter: true
    voxel_leaf_size: 0.10

    # 半径离群点过滤，专门去孤立噪声
    enable_radius_filter: true
    radius_filter_radius: 0.22
    radius_filter_min_neighbors: 2

    print_debug: true
